steps:
  - id: "Build and Push Docker Image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
    - -c
    - |
      echo "==== Building Docker Image ===="
      docker build -t ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/backend-motor-busqueda:latest .

      echo "==== Pushing Docker Image ===="
      docker push ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/backend-motor-busqueda:latest

  - id : "Deploy Image"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'motor-busqueda',
        '--image', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/backend-motor-busqueda:latest',
        '--region', '${_REGION}',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: "data-engineer-410822"
  _REGION: "us-east4"
  _REPO_NAME: "backend-motor-busqueda"